
on:
  workflow_dispatch:

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: austenstone/action-typescript
      - run: npm ci
      - run: npm run lint

  # Job 2: Reuses the anchor completely
  test-frontend:
    runs-on: ubuntu-latest
    # defaults: *frontend_defaults # ðŸ”— Injects working-directory and shell
    steps:
      - uses: actions/checkout@v4
        with: *checkout_with