on: workflow_dispatch

jobs:
  # Job 1: Defines the anchor
  lint-frontend:
    defaults: &frontend_defaults # âš“ï¸ Anchor defined here
      run:
        working-directory: ./apps/frontend
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: &checkout_withs # âš“ï¸ Anchor defined here
          repository: austenstone/action-typescript
      - run: npm ci
      - run: npm run lint

  # Job 2: Reuses the anchor completely
  test-frontend:
    runs-on: ubuntu-latest
    defaults: *frontend_defaults # ğŸ”— Injects working-directory and shell
    steps:
      - uses: actions/checkout@v4
        with: *checkout_with