name: Custom Action Composite
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: false
        default: 'Mona the Octocat'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v5
      - id: foo
        uses: austenstone/actions-playground/.github/actions/composite-action@main
        with:
          who-to-greet: ${{ github.event.inputs.who-to-greet }}
      # Use the output from the `foo` step
      - name: Get the output
        run: echo "The random number was ${{ steps.foo.outputs.random-number }}"