name: Defaults

on: workflow_dispatch

# Default settings for all jobs and steps
defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello World!'
      - run: echo $pwd
      - run: ps -p $$
    